config/routes.rb
Rails.application.routes.draw do
  
  
  
  resources :orders
  get 'shop/index'

  resources :carts
  resources :lineitems
  
  resources :carts do
	resources :lineitems
  end
  
  resources :products
  resources :customers
  get 'shop/index'

  resources :fitbits do
	resources :comments
  end
  
  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	get 'logout' => :destroy
	delete 'logout' => :destroy
  end
  
  resources :comments 
  
  get 'pages/home'

  get 'pages/about'
  
  get 'search', :to => 'fitbits#search'
  
  
  resources :fitbits

  
  resources :members
 
  

   root 'pages#home'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	
	has_many :lineitems
	
	def add_product(product_id)
		current_item = lineitems.find_by_product_id(product_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = lineitems.new(product_id: product_id)
			current_item.quantity = 1
		end	
		current_item ##returns a lineitem object
	end	
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :member
	belongs_to :fitbit
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :orders 
end

app/models/fitbit.rb
class Fitbit < ActiveRecord::Base
	has_many :members, dependent: :destroy
	has_many :comments, :dependent => :destroy
	
	def average_stars
		comments.average(:stars)
	end
	
	def self.search(query)
		where("name LIKE ?" , "%#{query}%")
	end
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
	belongs_to :cart
	belongs_to :product
	belongs_to :order
end

app/models/member.rb
class Member < ActiveRecord::Base
	belongs_to :fitbit
	has_many :comments
	has_secure_password
	validates_uniqueness_of :username
	validates_uniqueness_of :email
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/}
	
	
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :customer
	has_many :lineitems
	
	def add_lineitems_from_cart(cart)
		cart.lineitems.each do |item|
			item.cart_id = nil
			lineitems << item ##add an object to an array
		end
	end	
	
	def total_price(order)
		order.total = order.lineitems.inject(0){|sum,p| sum + (p.product.price * p.quantity)}
	end	
	
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :lineitems
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if@cart.id == session[:cart_id]
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
     def set_cart
      @cart = Cart.find(session[:cart_id])
	  rescue ActiveRecord::RecordNotFound
		@cart = Cart.create
		session[:cart_id] = @cart.id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/controllers/fitbits_controller.rb
class FitbitsController < ApplicationController
  before_action :set_fitbit, only: [:show, :edit, :update, :destroy]
   before_action :authorise, :only => [:new, :create, :edit, :update, :delete]

  # GET /fitbits
  # GET /fitbits.json
  def index
    @fitbits = Fitbit.all
  end

  # GET /fitbits/1
  # GET /fitbits/1.json
  def show
  end

  # GET /fitbits/new
  def new
    @fitbit = Fitbit.new
  end
  
  def search
	@fitbits = Fitbit.search params[:query]
	unless @fitbits.empty?
		render 'index'
	else 
		flash[:notice] = 'No record matches your search'
		render 'index'
	end
  end

  # GET /fitbits/1/edit
  def edit
  end

  # POST /fitbits
  # POST /fitbits.json
  def create
    @fitbit = Fitbit.new(fitbit_params)

    respond_to do |format|
      if @fitbit.save
        format.html { redirect_to @fitbit, notice: 'Fitbit was successfully created.' }
        format.json { render :show, status: :created, location: @fitbit }
      else
        format.html { render :new }
        format.json { render json: @fitbit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fitbits/1
  # PATCH/PUT /fitbits/1.json
  def update
    respond_to do |format|
      if @fitbit.update(fitbit_params)
        format.html { redirect_to @fitbit, notice: 'Fitbit was successfully updated.' }
        format.json { render :show, status: :ok, location: @fitbit }
      else
        format.html { render :edit }
        format.json { render json: @fitbit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fitbits/1
  # DELETE /fitbits/1.json
  def destroy
    @fitbit.destroy
    respond_to do |format|
      format.html { redirect_to fitbits_url, notice: 'Fitbit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fitbit
      @fitbit = Fitbit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fitbit_params
      params.require(:fitbit).permit(:name, :picture, :battery_life_in_hours, :colour, :display)
    end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def index
	@products = Product.order("title asc").all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


	def signed_in?
		if session[:member_id].nil?
			return
		else
			@current_member = Member.find_by_id(session[:member_id])
		end
	end
	
	def euro(price)
		number_to_currency(price, :unit => "€")
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/fitbits_helper.rb
module FitbitsHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/fitbits/_form.html.erb
<%= form_for(@fitbit) do |f| %>
  <% if @fitbit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fitbit.errors.count, "error") %> prohibited this fitbit from being saved:</h2>

      <ul>
      <% @fitbit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :battery_life_in_hours %><br>
    <%= f.number_field :battery_life_in_hours %>
  </div>
  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
  <div class="field">
    <%= f.label :display %><br>
    <%= f.text_field :display %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fitbits/_search.html.erb
<%= form_tag(search_path, method: :get) do %>
	<%= text_field_tag(:query, params[:query])%>
	<%= submit_tag "Search Fitbits" %>
<% end %>


app/views/fitbits/edit.html.erb
<h1>Editing Fitbit</h1>

<%= render 'form' %>

<%= link_to 'Show', @fitbit %> |
<%= link_to 'Back', fitbits_path %>

app/views/fitbits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fitbits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Picture</th>
      <th>Battery life in hours</th>
      <th>Colour</th>
      <th>Display</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fitbits.each do |fitbit| %>
      <tr>
        <td><%= fitbit.name %></td>
        <td><%= image_tag(fitbit.picture, :size => "50x50") %></td>
        <td><%= fitbit.battery_life_in_hours %></td>
        <td><%= fitbit.colour %></td>
        <td><%= fitbit.display %></td>
        <td><%= link_to 'Show', fitbit %></td>
        <td><%= link_to 'Edit', edit_fitbit_path(fitbit) %></td>
        <td><%= link_to 'Destroy', fitbit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fitbit', new_fitbit_path %>

app/views/fitbits/new.html.erb
<h1>New Fitbit</h1>

<%= render 'form' %>

<%= link_to 'Back', fitbits_path %>

app/views/fitbits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fitbit.name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag @fitbit.picture, :size => "100x100" %>
</p>

<p>
  <strong>Battery life in hours:</strong>
  <%= @fitbit.battery_life_in_hours %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @fitbit.colour %>
</p>

<p>
  <strong>Display:</strong>
  <%= @fitbit.display %>
</p>

<h2>Star Rating and comment:</h2>
	<%=form_for([@fitbit, Comment.new]) do |f| %>
	
		<h3><%=f.label :stars %>
			<% stars = [1,2,3,4,5] %>
			<% stars.each do |star| %>
				<%= f.radio_button :stars,star %><%= star %>
			<%end%>
		</h3></br>
		<%=f.text_area :content, :rows => 4, :cols => 40 %>
		<div class = "actions">
				<%=f.submit "Post a Comment"%>
		</div>
	<%end%>
	
	<% if @fitbit.comments.empty? %>
		<h3>You are the first to comment </h3>
	<%else%>
		<h2>What others felt about this:</h2>
		<% @fitbit.comments.reverse.each do |comment| %>
			<p><%= comment.content %>
			Posted <%= time_ago_in_words(comment.created_at) %> ago by
			<%=comment.member.name %></p>
		<%end%>
		<h3>Star Rating</h3>
		<p>
			<%= number_with_precision(@fitbit.average_stars, precision: 0)%>
		</p>
	<%end%>

<%= link_to 'Edit', edit_fitbit_path(@fitbit) %> |
<%= link_to 'Back', fitbits_path %>