config/routes.rb
Rails.application.routes.draw do
  
  
  
  resources :orders
  get 'shop/index'

  resources :carts
  resources :lineitems
  
  resources :carts do
	resources :lineitems
  end
  
  resources :products
  resources :customers
  get 'shop/index'

  resources :fitbits do
	resources :comments
  end
  
  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	get 'logout' => :destroy
	delete 'logout' => :destroy
  end
  
  resources :comments 
  
  get 'pages/home'

  get 'pages/about'
  
  get 'search', :to => 'fitbits#search'
  
  
  resources :fitbits

  
  resources :members
 
  

   root 'pages#home'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	
	has_many :lineitems
	
	def add_product(product_id)
		current_item = lineitems.find_by_product_id(product_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = lineitems.new(product_id: product_id)
			current_item.quantity = 1
		end	
		current_item ##returns a lineitem object
	end	
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :member
	belongs_to :fitbit
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :orders 
end

app/models/fitbit.rb
class Fitbit < ActiveRecord::Base
	has_many :members, dependent: :destroy
	has_many :comments, :dependent => :destroy
	
	def average_stars
		comments.average(:stars)
	end
	
	def self.search(query)
		where("name LIKE ?" , "%#{query}%")
	end
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
	belongs_to :cart
	belongs_to :product
	belongs_to :order
end

app/models/member.rb
class Member < ActiveRecord::Base
	belongs_to :fitbit
	has_many :comments
	has_secure_password
	validates_uniqueness_of :username
	validates_uniqueness_of :email
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/}
	
	
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :customer
	has_many :lineitems
	
	def add_lineitems_from_cart(cart)
		cart.lineitems.each do |item|
			item.cart_id = nil
			lineitems << item ##add an object to an array
		end
	end	
	
	def total_price(order)
		order.total = order.lineitems.inject(0){|sum,p| sum + (p.product.price * p.quantity)}
	end	
	
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :lineitems
end

app/helpers/application_helper.rb
module ApplicationHelper


	def signed_in?
		if session[:member_id].nil?
			return
		else
			@current_member = Member.find_by_id(session[:member_id])
		end
	end
	
	def euro(price)
		number_to_currency(price, :unit => "€")
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/fitbits_helper.rb
module FitbitsHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
<html>
<head>
 
  <title>Fitbit1app</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  

 </head>

<body>
<div id="banner">
	<%=image_tag("fitbits.jpg",:size => "100x50") %>
	<%="FitBits" %>
	<%= render '/fitbits/search' %>
	
<% flash.each do |key, value| %>
	<div class="flash <%= key %>">
		<%=value %>
<% end %>
	
	
</div>

<div class="container">
	<ul class="nav nav-tabs">
	<% if !signed_in? %>
			<li><%=link_to "Sign In", login_path %></li>
		<%else%>
			<li>Signed in as <%= @current_member.name%></li>
			<li><%=link_to "Sign Out", logout_path %></li>
		<%end%>
		
		<li><%= link_to "About", root_path%></li>
		<li><%=link_to "Fitbits", fitbits_path%></li>
		<li><%=link_to "Members", members_path%></li>
		<li><%=link_to "Buy FitBits",'/shop/index' %></li>
	</ul>
	 



		<%= yield %>
	</div>
 </div>
	

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
					
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                   
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
					
						
						<section id="brand" class="container content-section text-center">
						
							<div class="row">
							 <div class="col-md-8 col-md-offset-2">
								<h2>Fitbit</h2>
                        <p class="intro-text">Find your fit with Fitbit's family of fitness products that help you stay
						<br>motivated and improve your health by tracking your activity, exercise, food, weight and sleep.</p>
                        <a href="#about" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Who We Are</h2>
                <p>Fitbit is a passionate company dedicated to health and fitness who are building products to help transform peoples lives.</p>
                <p>While health can be serious business, fitbit feels it doesn't have to be.</p>
                <p>Fitbit believe you're more likely to reach your goals if your encouraged to have fun, smile, and feel empowered along the way.</p>
            </div>
        </div>
    </section>

    <!-- GitHub Section -->
    <section id="download" class="content-section text-center">
        <div class="github-section">
            <div class="container">
                <div class="col-lg-8 col-lg-offset-2">
                    <h2>See my GitHub</h2>
                    <p>My name is Keelin O'Farrell and my GitHub link name is keelinofarrell</p>
                    <a href="https://github.com/" class="btn btn-default btn-lg">Visit Visit Page</a>
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Contact Fitbit</h2>
                <p>Feel free to email us to provide some feedback on our fitbits, give us suggestions for new ideas, or to just say hello!</p>
                <p><a href="mailto:feedback@fitbits.com">feedback@fitbit.com</a>
                </p>
                <ul class="list-inline banner-social-buttons">
                    <li>
                        <a href="https://twitter.com/FitbitSupport/with_replies" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                    </li>
                    <li>
                        <a href="https://www.facebook.com/fitbit/" class="btn btn-default btn-lg"><i class="fa fa-facebook fa-fw"></i> <span class="network-name">Facebook</span></a>
                    </li>
                    <li>
                        <a href="https://plus.google.com/+fitbit" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </section>

    <!-- Map Section -->
	
	
	
	
	
    <div id="map">
	
	<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{53.3382}%2C#{6.2591}"%>
	
	</div>